# -*- coding: utf-8 -*-
"""Jacto.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bBpq5J7vv-ROObFgLc0SzLhUxGOBEPCX
"""

!nvidia-smi

import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/Documentos/CarsData.csv", sep=',')

print(df.head())

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("/content/drive/MyDrive/Documentos/CarsData.csv")

plt.figure(figsize=(10, 6))
df['year'].value_counts().sort_index().plot(kind='bar')
plt.title('Contagem de Carros por Ano')
plt.xlabel('Ano')
plt.ylabel('Contagem')
plt.xticks(rotation=45)
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("/content/drive/MyDrive/Documentos/CarsData.csv")

top_10_modelos = df['model'].value_counts().nlargest(10)

df_filtrado = df[df['model'].isin(top_10_modelos.index)]

plt.figure(figsize=(10, 6))
df_filtrado['model'].value_counts().plot(kind='bar')
plt.title('Contagem de Carros por Modelo (Top 10)')
plt.xlabel('Modelo')
plt.ylabel('Contagem')
plt.xticks(rotation=45)
plt.show()



