# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bMvcCLUjbaVzFK6Icyx2H6vSjXw8J8sR
"""

!nvidia-smi

!pip install ultralytics
from ultralytics import YOLO
import os
from IPython.display import display, Image
from IPython import display

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="yisq6S7o0lmmVfwfQfUX")
project = rf.workspace("corn-leaf-disease").project("soundcheck")
version = project.version(8)
dataset = version.download("yolov8")

!yolo task=detect mode=train model=yolov8n.pt data='/content/soundcheck-8/data.yaml' epochs=30 imgsz=640

!pip install ultralytics
from ultralytics import YOLO

model= YOLO('/content/runs/detect/train/weights/best.pt')

model.export(format='ONNX')

!yolo task=detect mode=val model='/content/runs/detect/train/weights/best.onnx' data='/content/soundcheck-8/data.yaml'

from google.colab import drive
drive.mount('/content/drive')

!yolo task=detect mode=predict model='/content/runs/detect/train/weights/best.onnx' conf=0.5 source='/content/drive/MyDrive/Pet Match/Petmatch/Documentação/milhos_folhas.mp4' imgsz=640

!yolo task=detect mode=predict model='/content/runs/detect/train/weights/best.onnx' conf=0.5 source='/content/drive/MyDrive/Pet Match/Petmatch/Documentação/praga.mp4' imgsz=640

!yolo task=detect mode=predict model='/content/runs/detect/train/weights/best.onnx' conf=0.5 source='/content/drive/MyDrive/Pet Match/Petmatch/Documentação/manchas.mp4' imgsz=640